services:
  milvus-etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: milvus-etcd
    restart: always
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    ports: []

  milvus-minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    container_name: milvus-minio
    command: server /data
    restart: always
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data

  milvus:
    image: milvusdb/milvus:v2.3.9
    container_name: milvus
    restart: always
    depends_on:
      - milvus-etcd
      - milvus-minio
    environment:
      - ETCD_ENDPOINTS=milvus-etcd:2379
      - MINIO_ADDRESS=milvus-minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MILVUS_CLUSTER_ENABLED=true
      - MILVUS_REPLICA_NUMBER=2
    ports: []

  fastapi1:
    build: .
    container_name: fastapi1
    restart: always
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    # ports:  # Đã bỏ publish cổng, chỉ expose nội bộ cho nginx
    #   - "8000:8000"
    volumes:
      - ./images/train1:/app/images/train
      - ./example.db:/app/example.db
    depends_on:
      - milvus

  fastapi2:
    build: .
    container_name: fastapi2
    restart: always
    command: uvicorn app:app --host 0.0.0.0 --port 8001
    # ports:  # Đã bỏ publish cổng, chỉ expose nội bộ cho nginx
    #   - "8001:8001"
    volumes:
      - ./images/train2:/app/images/train
      - ./example.db:/app/example.db
    depends_on:
      - milvus

  fastapi3:
    build: .
    container_name: fastapi3
    restart: always
    command: uvicorn app:app --host 0.0.0.0 --port 8002
    # ports:  # Đã bỏ publish cổng, chỉ expose nội bộ cho nginx
    #   - "8002:8002"
    volumes:
      - ./images/train3:/app/images/train
      - ./example.db:/app/example.db
    depends_on:
      - milvus

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi1
      - fastapi2
      - fastapi3

volumes:
  minio_data: